// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVn9W3ZSIg-BNi6DwGPxdaA1msS6sw8k',
    appId: '1:224401761369:web:c856068b634e752fca3d48',
    messagingSenderId: '224401761369',
    projectId: 'dttracker-92abc',
    authDomain: 'dttracker-92abc.firebaseapp.com',
    storageBucket: 'dttracker-92abc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEYOswdlhUBTQbq0YdQjX7WVcGAhzmxxg',
    appId: '1:224401761369:android:cbfb69e5880ca22bca3d48',
    messagingSenderId: '224401761369',
    projectId: 'dttracker-92abc',
    storageBucket: 'dttracker-92abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbVbxsdF4hVwlynGvdDUkgViX9tzmEGwE',
    appId: '1:224401761369:ios:0ce2ee13c3a5814aca3d48',
    messagingSenderId: '224401761369',
    projectId: 'dttracker-92abc',
    storageBucket: 'dttracker-92abc.appspot.com',
    iosBundleId: 'com.example.dtTrackerUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbVbxsdF4hVwlynGvdDUkgViX9tzmEGwE',
    appId: '1:224401761369:ios:23c5a969927f877dca3d48',
    messagingSenderId: '224401761369',
    projectId: 'dttracker-92abc',
    storageBucket: 'dttracker-92abc.appspot.com',
    iosBundleId: 'com.example.dtTrackerUser.RunnerTests',
  );
}
